// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXQh4O6flU_JD207eEGf2HlZMNabHWNww',
    appId: '1:447943473094:web:e2b5c8d311ac7dc3bda4c7',
    messagingSenderId: '447943473094',
    projectId: 'evently-a2b88',
    authDomain: 'evently-a2b88.firebaseapp.com',
    storageBucket: 'evently-a2b88.firebasestorage.app',
    measurementId: 'G-2WXXB49NS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB40kO6iysU7x6OW-zwZVgDUv0qX8GIy0',
    appId: '1:447943473094:android:dc0029bbdee79df6bda4c7',
    messagingSenderId: '447943473094',
    projectId: 'evently-a2b88',
    storageBucket: 'evently-a2b88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkUlWjcQTz2clykyzmWI5TxdZjMGRC12A',
    appId: '1:447943473094:ios:156ab6332bfd2595bda4c7',
    messagingSenderId: '447943473094',
    projectId: 'evently-a2b88',
    storageBucket: 'evently-a2b88.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkUlWjcQTz2clykyzmWI5TxdZjMGRC12A',
    appId: '1:447943473094:ios:156ab6332bfd2595bda4c7',
    messagingSenderId: '447943473094',
    projectId: 'evently-a2b88',
    storageBucket: 'evently-a2b88.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXQh4O6flU_JD207eEGf2HlZMNabHWNww',
    appId: '1:447943473094:web:fd6d4de469004555bda4c7',
    messagingSenderId: '447943473094',
    projectId: 'evently-a2b88',
    authDomain: 'evently-a2b88.firebaseapp.com',
    storageBucket: 'evently-a2b88.firebasestorage.app',
    measurementId: 'G-BKGB9ZWRB4',
  );
}
